monolog:
    channels:
        - deprecation
        - domain_events

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                formatter: monolog.formatter.json
                channels: ["!event", "!messenger", "!domain_events"]
            domain_events:
                type: stream
                path: "%kernel.logs_dir%/domain_events.log"
                level: debug
                formatter: monolog.formatter.json
                channels: ["messenger", "domain_events"]

when@test:
    monolog:
        handlers:
            main:
                type: 'null'

when@prod:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: info
                formatter: monolog.formatter.json
                channels: ["!deprecation"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
